# Generated by Django 2.2.1 on 2019-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0008_auto_20191029_1535'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comedians',
        ),
        migrations.AddField(
            model_name='event',
            name='comedians',
            field=models.ManyToManyField(to='comedians.RegisterComedian'),
        ),
    ]
