# Generated by Django 2.2.1 on 2019-11-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0008_auto_20191029_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomedian',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
