# Generated by Django 2.2.1 on 2019-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0009_registercomedian_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pp.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
