# Generated by Django 2.2.1 on 2019-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0010_auto_20191108_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='videos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
