# Generated by Django 2.2.1 on 2019-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0011_auto_20191109_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_pp.png', null=True, upload_to='profile_pic'),
        ),
    ]
