# Generated by Django 2.2.1 on 2019-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0012_auto_20191109_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
